# Generated by Django 2.2.3 on 2019-09-10 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_accessories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('season', models.CharField(choices=[('Wi', 'Winter'), ('Sp', 'Spring'), ('Su', 'Summer'), ('Fa', 'Fall')], default='Wi', max_length=2)),
                ('planner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Planner')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
    ]
