# Generated by Django 2.2.3 on 2019-09-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20190910_2159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gadget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='planner',
            name='gadgets',
            field=models.ManyToManyField(to='main_app.Gadget'),
        ),
    ]
