# Generated by Django 2.2.3 on 2019-09-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_auto_20190911_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accessory',
            name='date',
            field=models.DateField(verbose_name='accessory date'),
        ),
    ]
